#!/usr/bin/env bash

configfilescommon=(
	$HOME/.bashrc
	$HOME/.bashaliases
	$HOME/.vimrc
)

configfilesremote=(
	$HOME/.bashremote
)

COPY_TARGET_DIR=$1

shopt -s dotglob

for i in "${configfilescommon[@]}"; do
	cp $i $COPY_TARGET_DIR
done

shopt -u dotglob
