#!/usr/bin/env bash

configfilescommon=(
	~/.bashrc
	~/.bashaliases
	~/.vimrc
)

configfilesremote=(
	~/.bashremote
)

COPY_TARGET_DIR=$1

shopt -s dotglob

for i in "${configfilescommon[@]}"; do
	cp $i $COPY_TARGET_DIR/.
done

shopt -u dotglob
