#!/usr/bin/env bash

CUR_DIR="$PWD"

GIT_REPO_NAMES=(
	configs
	scripts
)

pull(){
	cd $1
	git pull
	cd $CUR_DIR
}

push(){
	cd $1
	git add -A
	git commit -m "automatic update"
	git push
	cd $CUR_DIR
}

# copy over settings to the repository folder
COPY_TARGET_DIR="$HOME/configs/common"

bash $HOME/scripts/configs/commands/copy $COPY_TARGET_DIR &
echo "pull and then pushing to repo "

for i in "${GIT_REPO_NAMES[@]}";
do
	echo "$i"
	pull "$HOME/$i"
	push "$HOME/$i"
done

